### ISSUE TITLE
WorldEditBoundaryAssertion throws NullPointerException when actor is null

### ISSUE THREAD

**Issue by stefvanschie** [stefvanschie/buildinggame#137]
_Redirected issue from different source_

## Issue

__I'm using version:__ *unknown*  
__I'm on Minecraft:__ *1.12.2*  
__I'm running:__ *Paper*

__Seen results:__  
A NullPointerException is thrown when the actor in the EditSessionEvent is null.

__Expected results:__  
The plugin should ignore the EditSessionEvent without making any changes to the event.

__How to reproduce:__  
*unknown*

__Additional info:__ 
Error log:
```
[WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.extent.EditSessionEvent@26107a11 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [WorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.wrapExtent(EditSession.java:520) [FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:320) [FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:166) [FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:161) [FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:359) [FastAsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:215) [WorldEdit.jar:?]
        at com.gmail.stefvanschiedev.buildinggame.timers.VoteTimer$1.run(VoteTimer.java:159) [buildinggame.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1313]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1313]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 15 more
Caused by: java.lang.NullPointerException
        at com.gmail.stefvanschiedev.buildinggame.events.softdependencies.WorldEditBoundaryAssertion.onEditSession(WorldEditBoundaryAssertion.java:38) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 15 more
```

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.
