### ISSUE TITLE
Fix ConcurrentModificationException when saving statistics to database

### ISSUE THREAD

**Issue by stefvanschie** [stefvanschie/buildinggame#142]
*Redirected issue from different source*

## Issue

__I'm using version:__ *5.8.2*  
__I'm on Minecraft:__ *1.12.2*  
__I'm running:__ *Paper*

__Seen results:__  
When statistics have to be saved to the database, a ConcurrentModificationException is thrown.

__Expected results:__  
No exception should occur when saving statistics to the database.

__How to reproduce:__  
Make a statistic register by playing games at the same time the statistics are being saved to the database.

__Additional info:__ 
Stack trace:

    [11:29:08 WARN]: [BuildingGame] Plugin BuildingGame v5.8.2 generated an exception while executing task 42
    java.util.ConcurrentModificationException: null
            at java.util.ArrayList.forEach(ArrayList.java:1260) ~[?:1.8.0_171]
            at com.gmail.stefvanschiedev.buildinggame.managers.stats.StatManager.lambda$saveToDatabase$8(StatManager.java:217) ~[?:?]
            at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[?:1.8.0_171]
            at com.gmail.stefvanschiedev.buildinggame.managers.stats.StatManager.saveToDatabase(StatManager.java:217) ~[?:?]
            at com.gmail.stefvanschiedev.buildinggame.timers.StatSaveTimer.run(StatSaveTimer.java:24) ~[?:?]
            at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1313]
            at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1313]
            at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1313]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
            at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

Instead of using an ArrayList as backing array for the statistics, put it in a `Collections#synchronizedList` call and use the returned object as backing array. Every method that iterates over these values in some way should be marked as synchronized.

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.
