### ISSUE TITLE
Reload command throws NullPointerException when executed

### ISSUE THREAD

**Issue by stefvanschie** [stefvanschie/buildinggame#149]
*Redirected issue from different source*

## Issue

__I'm using version:__ *unknown*  
__I'm on Minecraft:__ *1.12*  
__I'm running:__ *unknown*

__Seen results:__  
When performing the */buildinggame reload* command, an internal error occurs.

__Expected results:__  
The */buildinggame reload* command should function properly when executed and not throw any exceptions.

__How to reproduce:__  
Run the */buildinggame reload* command.

__Additional info:__  
Error log:

    [12:52:08 INFO]: I'm sorry, but there was an error performing this command.
    [12:52:08 ERROR]: [ACF] Exception in command: buildinggame reload
    [12:52:08 ERROR]: [ACF] java.lang.reflect.InvocationTargetException
    [12:52:08 ERROR]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [12:52:08 ERROR]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [12:52:08 ERROR]: [ACF] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [12:52:08 ERROR]: [ACF] at java.lang.reflect.Method.invoke(Unknown Source)
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.acf.RegisteredCommand.invoke(RegisteredCommand.java:146)
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.acf.BaseCommand.executeCommand(BaseCommand.java:467)
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.acf.BaseCommand.execute(BaseCommand.java:370)
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.acf.RootCommand.execute(RootCommand.java:69)
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.acf.BukkitRootCommand.execute(BukkitRootCommand.java:63)
    [12:52:08 ERROR]: [ACF] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
    [12:52:08 ERROR]: [ACF] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:629)
    [12:52:08 ERROR]: [ACF] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:615)
    [12:52:08 ERROR]: [ACF] at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:408)
    [12:52:08 ERROR]: [ACF] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:372)
    [12:52:08 ERROR]: [ACF] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651)
    [12:52:08 ERROR]: [ACF] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555)
    [12:52:08 ERROR]: [ACF] at java.lang.Thread.run(Unknown Source)
    [12:52:08 ERROR]: [ACF] Caused by: java.lang.NullPointerException
    [12:52:08 ERROR]: [ACF] at com.gmail.stefvanschiedev.buildinggame.managers.commands.CommandManager.onReload(CommandManager.java:347)
    [12:52:08 ERROR]: [ACF] ... 17 more

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.
