### ISSUE TITLE
/bg not working

### ISSUE THREAD

**Issue by Refinedgiant888** [stefvanschie/buildinggame#161]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ *latest*  
__I'm on Minecraft:__ *1.12.2*  
__I'm running:__ *Bukkit*

__Seen results:__  
*Okay so for some reason /bg is not showing me anything. the plugin is installed properly and I am using multiworld plugin. The /bg does not work in any of the server worlds and when I type it in, it does not show anything. please help.*

__Expected results:__  
*/bg should have shown me a list of commands and I even tried all the other commands for /bg.*

__How to reproduce:__  
*make a new world with multiworld and type /bg in any world *

__Additional info:__  
*link to my plugins https://imgur.com/UDUgocY *

**Comment by stefvanschie** [comment]
Please use the latest Building Game version; version 5.8.6. If the error still persists in this version, please re-open this issue with the new information (e.g. error logs, warnings, configurations etc.).

**Comment by Refinedgiant888** [comment]
[ERROR] [BuildingGame] Plugin BuildingGame v5.8.6 has failed to register events for class com.gmail.stefvanschiedev.buildinggame.events.entity.EntitySpawn because org/bukkit/event/entity/EntitySpawnEvent does not exist.

[INFO] [BuildingGame] Loading signs

[ERROR] Error occurred while enabling BuildingGame v5.8.6 (Is it up to date?)

java.lang.NullPointerException: null

at org.bukkit.Location.getBlock(Location.java:91) ~[craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.setup(SignManager.java:96) ~[?:?]

at com.gmail.stefvanschiedev.buildinggame.Main.loadPlugin(Main.java:360) ~[?:?]

at com.gmail.stefvanschiedev.buildinggame.Main.onEnable(Main.java:120) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
