### ISSUE TITLE
/bg still not working

### ISSUE THREAD

**Issue by Refinedgiant888** [stefvanschie/buildinggame#162]
You can discard this template if you're submitting a code fix/spelling mistake etc. Don't discard this when you're submitting a bug

Issue
I'm using version: 5.8.6
I'm on Minecraft: 1.12.2
I'm running: Bukkit

Seen results:
Okay so for some reason /bg is not showing me anything. the plugin is installed properly and I am using multiworld plugin. The /bg does not work in any of the server worlds and when I type it in, it does not show anything. please help.

Expected results:
/bg should have shown me a list of commands and I even tried all the other commands for /bg.

How to reproduce:
*make a new world with multiworld and type /bg in any world *

Additional info:
*link to my plugins https://imgur.com/UDUgocY *

[ERROR] [BuildingGame] Plugin BuildingGame v5.8.6 has failed to register events for class com.gmail.stefvanschiedev.buildinggame.events.entity.EntitySpawn because org/bukkit/event/entity/EntitySpawnEvent does not exist.

[INFO] [BuildingGame] Loading signs

[ERROR] Error occurred while enabling BuildingGame v5.8.6 (Is it up to date?)

java.lang.NullPointerException: null

at org.bukkit.Location.getBlock(Location.java:91) ~[craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.setup(SignManager.java:96) ~[?:?]

at com.gmail.stefvanschiedev.buildinggame.Main.loadPlugin(Main.java:360) ~[?:?]

at com.gmail.stefvanschiedev.buildinggame.Main.onEnable(Main.java:120) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-57ab4cf]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

**Comment by stefvanschie** [comment]
Successfully reproduced, will be fixed in version 5.9.0.

Developer information (if you aren't assigned to this issue you can ignore this):
_No default command handler is specified for commands without additional arguments. Ensure that the default command handler shows a help menu listing the sub commands which can be used, by making use of built-in ACF functionality._

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.

Version 5.9.0 will resolve this issue.
