### ISSUE TITLE
Spectator mode error in console 

### ISSUE THREAD

**Issue by WolfMaster333** [stefvanschie/buildinggame#3]
1.Also I not able to subject vote menu.
2.When I left the arena the following error is in console.
Could not pass event PlayerMoveEvent to BuildingGame v1.13.1
org.bukkit.event.EventException
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at us.Myles.PWP.TransparentListeners.PWPTimedRegisteredListener.callEvent(Unknown Source) [PerWorldPlugins-DEV.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
        at com.gmail.stefvanschiedev.buildinggame.events.player.Move.onPlayerMove(Move.java:47) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        ... 18 more
[21:02:00 ERROR]:  THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS 
Could not pass event PlayerMoveEvent to BuildingGame v1.13.1
org.bukkit.event.EventException
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at us.Myles.PWP.TransparentListeners.PWPTimedRegisteredListener.callEvent(Unknown Source) [PerWorldPlugins-DEV.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-"c0e7853"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
        at com.gmail.stefvanschiedev.buildinggame.events.player.Move.onPlayerMove(Move.java:47) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        ... 18 more

**Comment by stefvanschie** [comment]
1. Don't you get the paper to open the inventory to vote? Or doesn't register your vote?
2. Will fix it in the next version.

**Comment by WolfMaster333** [comment]
Doesn't give me the paper.

**Comment by stefvanschie** [comment]
Make sure you have the permission _bg.subjectmenu_

**Comment by WolfMaster333** [comment]
Please add this permission on bukkit and spigot :+1:

**Comment by stefvanschie** [comment]
Fixed in latest version (2.0.3).
