### ISSUE TITLE
Mysql stats refuse to work / SQL Table not created

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#34]
I just setup correct my database config but the plugin refuse to use the mysql connection, but when some user join it say that the plugin fail to create the mysql table... using 1.8.8 and BG 4.0.2
`[01:28:28] [Server thread/INFO]: [BuildingGame] Total connections ==> 10
[01:28:28] [Server thread/WARN]: [BuildingGame] Database usage failed; returning to flat-file storage
[01:28:28] [Server thread/INFO]: [BuildingGame] Loading listeners
[01:28:28] [Server thread/INFO]: [BuildingGame] Loading signs
[01:28:28] [Server thread/INFO]: [BuildingGame] Loading timer
[01:28:28] [Server thread/INFO]: [BuildingGame] BuildingGame has been enabled in 2347 milliseconds!
[01:55:08] [Thread-11/INFO]: UUID of player NoobGamer is 52d243b9-b750-3ef8-a4c8-e172d7686127
[01:55:08] [Server thread/INFO]: NoobGamer[/73.76.206.2:43428] logged in with entity id 0 at ([buildbattle]230.5, 60.0, 383.5)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'minecraft.buildinggamestats' doesn't exist
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.gmail.stefvanschiedev.buildinggame.managers.stats.MySQLDatabase.executeQuery(MySQLDatabase.java:81)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.gmail.stefvanschiedev.buildinggame.managers.stats.MySQLDatabase.insertPlayer(MySQLDatabase.java:97)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at com.gmail.stefvanschiedev.buildinggame.events.stats.database.JoinPlayerStats$1.run(JoinPlayerStats.java:25)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[01:55:08] [Craft Scheduler Thread - 4/WARN]: [BuildingGame] Failed to execute request: SELECT UUID FROM buildinggamestats WHERE UUID='52d243b9-b750-3ef8-a4c8-e172d7686127'
[01:55:08] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[01:55:08] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin BuildingGame v4.0.2 generated an exception while executing task 32065
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.gmail.stefvanschiedev.buildinggame.managers.stats.MySQLDatabase.insertPlayer(MySQLDatabase.java:100)
	at com.gmail.stefvanschiedev.buildinggame.events.stats.database.JoinPlayerStats$1.run(JoinPlayerStats.java:25)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[01:56:01] [Server thread/INFO]: NoobGamer lost connection: Disconnected
[01:56:01] [Server thread/INFO]: NoobGamer left the game.
[01:56:01] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[01:56:01] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin BuildingGame v4.0.2 generated an exception while executing task 33120
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.gmail.stefvanschiedev.buildinggame.events.stats.database.QuitPlayerStats$1.run(QuitPlayerStats.java:24)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
`

**Comment by stefvanschie** [comment]
Did you create the database by yourself? The database has to be created by yourself, only the SQL table will be created by the plugin.

**Comment by xion87** [comment]
The database already exist, the plugin fail to create the table

**Comment by stefvanschie** [comment]
I see apparently, the code thinks it fails when it works, and it works when it fails. I'll fix this in the next version.
