### ISSUE TITLE
Plugin breaks after voting

### ISSUE THREAD

**Issue by Tharylia** [stefvanschie/buildinggame#381]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ *12.0.0*  
__I'm on Minecraft:__ *1.19.3*  
__I'm running:__ *Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)*

__Seen results:__  
*The plugin breaks after voting (played alone for testing) and does not return the player to the main spawn:*

[13:45:37 WARN]: [BuildingGame] Task #64391 for BuildingGame v12.0.0 generated an exception
java.lang.IllegalArgumentException: java.lang.ClassCastException@1b745052
        at jdk.internal.reflect.GeneratedConstructorAccessor83.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.gameplayer.GamePlayer.refreshChunk(GamePlayer.java:362) ~[buildinggame-12.0.0.jar:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$22(Plot.java:735) ~[buildinggame-12.0.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$23(Plot.java:735) ~[buildinggame-12.0.0.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$24(Plot.java:734) ~[buildinggame-12.0.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.restore(Plot.java:734) ~[buildinggame-12.0.0.jar:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.arena.Arena.lambda$nextMatch$42(Arena.java:1524) ~[buildinggame-12.0.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.arena.Arena.nextMatch(Arena.java:1523) ~[buildinggame-12.0.0.jar:?]
        at com.gmail.stefvanschiedev.buildinggame.timers.WinTimer.run(WinTimer.java:41) ~[buildinggame-12.0.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-366]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-366]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

__Expected results:__  
*Return to spawn after voting completes*

__How to reproduce:__  
*See results*

__Additional info:__

**Comment by stefvanschie** [comment]
Thank you for the report, this has been fixed in version 12.1.0.
