### ISSUE TITLE
[BUG] Can't finish the game.

### ISSUE THREAD

**Issue by HollyAssasin** [stefvanschie/buildinggame#418]
## Issue

__I'm using version:__ 12.4.0
__I'm on Minecraft:__ 1.19.4
__I'm running:__ Paper

__Seen results:__  
After building time is over, it should teleport to different plots to let people vote, yet it teleports all to a single plot only and doesn't allow voting. In the end nobody is the winner and the game doesn't stop and doesn't teleport back to main spawn.

__Expected results:__  
Teleport to different plots, voting, show the winner and teleport back to main spawn.

__How to reproduce:__  
Play the game normally.

__Additional info:__  
Throws the same error after the game is finished:
```
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at com.gmail.stefvanschiedev.buildinggame.nms.v1_19_4.NMSManagerImpl.refreshChunk(NMSManagerImpl.java:37) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.gameplayer.GamePlayer.refreshChunk(GamePlayer.java:342) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$21(Plot.java:779) ~[buildinggame-12.4.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$22(Plot.java:779) ~[buildinggame-12.4.0.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.lambda$restore$23(Plot.java:778) ~[buildinggame-12.4.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.restore(Plot.java:778) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.game.WinningGamePhase.nextMatch(WinningGamePhase.java:530) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.game.WinningGamePhase.onPhaseEnd(WinningGamePhase.java:133) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.game.util.timed.TimedGamePhase.endPhase(TimedGamePhase.java:272) ~[buildinggame-12.4.0.jar:?]
	at com.gmail.stefvanschiedev.buildinggame.game.util.timed.TimedGamePhase$1.run(TimedGamePhase.java:164) ~[buildinggame-12.4.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by stefvanschie** [comment]
Thank you for your report, this should be fixed with version 1.20.5.
