### ISSUE TITLE
Unable to use to setspawn for an arena in PaperMC

### ISSUE THREAD

**Issue by goldenlib** [stefvanschie/buildinggame#455]
## Issue

__I'm using version:__ *12.7.0 (but i also tested on other version*  
__I'm on Minecraft:__ *1.21*  
__I'm running:__ *Paper 1.21-109*

__Seen results:__  
When i try the command /buildinggame:bg setspawn myarena, in the chat i see _"I'm sorry, but there was an error performing this command"_ and the console show this:

`[00:47:25 ERROR]: [ACF] Exception in command: buildinggame setspawn wood
[00:47:25 ERROR]: [ACF] java.lang.IllegalArgumentException: SOUL_FIRE isn't an item
[00:47:25 ERROR]: [ACF] 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[00:47:25 ERROR]: [ACF] 	at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
[00:47:25 ERROR]: [ACF] 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
[00:47:25 ERROR]: [ACF] 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
[00:47:25 ERROR]: [ACF] 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
[00:47:25 ERROR]: [ACF] 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.utils.guis.buildmenu.FloorMenu.<init>(FloorMenu.java:171)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.utils.guis.buildmenu.BuildMenu.<init>(BuildMenu.java:90)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.<init>(Plot.java:161)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.managers.commands.CommandManager.onSetSpawn(CommandManager.java:717)
[00:47:25 ERROR]: [ACF] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[00:47:25 ERROR]: [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.acf.BaseCommand.execute(BaseCommand.java:513)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.acf.RootCommand.execute(RootCommand.java:99)
[00:47:25 ERROR]: [ACF] 	at buildinggame-12.7.0.jar//com.gmail.stefvanschiedev.buildinggame.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[00:47:25 ERROR]: [ACF] 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[00:47:25 ERROR]: [ACF] 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317)
[00:47:25 ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[00:47:25 ERROR]: [ACF] 	at java.base/java.lang.Thread.run(Thread.java:1583)
`

__How to reproduce:__  
I used Papermc  1.21 and Java21. I tried to remove all the other plugin to verify it's not a conflict thing.

__Additional info:__  
When the config file is absent, it can launch but after this error shows up, if i restart the server, the plugin is broken en display similar errors. Because it could be a paper thing, i tried different version an always have the same result.

**Comment by stefvanschie** [comment]
Thank you for the report, this will be fixed in the next version.

**Comment by stefvanschie** [comment]
This issue has been fixed in version 12.7.1.
