### ISSUE TITLE
BG today stop working fully!!!!

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#48]
[08:55:24 WARN]: [BuildingGame] Task #4 for BuildingGame v4.0.5 generated an exception
java.lang.ExceptionInInitializerError
	at com.gmail.stefvanschiedev.buildinggame.timers.ScoreboardUpdater.run(ScoreboardUpdater.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Display name '§l§3[Битва Строителей] Статистика' is longer than the limit of 32 characters
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:40) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at com.gmail.stefvanschiedev.buildinggame.utils.scoreboards.MainScoreboard.<init>(MainScoreboard.java:36) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.managers.scoreboards.MainScoreboardManager.<init>(MainScoreboardManager.java:13) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.managers.scoreboards.MainScoreboardManager.<clinit>(MainScoreboardManager.java:35) ~[?:?]
	... 8 more
[08:55:24 ERROR]: Could not pass event PlayerJoinEvent to BuildingGame v4.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.gmail.stefvanschiedev.buildinggame.managers.scoreboards.MainScoreboardManager
	at com.gmail.stefvanschiedev.buildinggame.events.scoreboards.MainScoreboardJoinShow.onPlayerJoin(MainScoreboardJoinShow.java:19) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	... 16 more

**Comment by BabelSolea** [comment]
[09:15:44 ERROR]: Could not pass event PlayerJoinEvent to BuildingGame v4.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.gmail.stefvanschiedev.buildinggame.managers.scoreboards.MainScoreboardManager
	at com.gmail.stefvanschiedev.buildinggame.events.scoreboards.MainScoreboardJoinShow.onPlayerJoin(MainScoreboardJoinShow.java:19) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	... 16 more

**Comment by stefvanschie** [comment]
Your scoreboard header: _§l§3[Битва Строителей] Статистика_ is longer than 32 characters (it's 33). Stop your server, edit the text in the config.yml so it's 32 characters or less and start your server again. That should fix the issue.

**Comment by BabelSolea** [comment]
ok i did that and some errors gone.

**Comment by stefvanschie** [comment]
Alright, glad it worked. Closing this for now, feel free to open it again when the same error occurs again.
