### ISSUE TITLE
subjects!

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#51]
![image](https://cloud.githubusercontent.com/assets/23665302/24585861/0aab1d44-179d-11e7-895d-fccbeb792eb9.png)

![image](https://cloud.githubusercontent.com/assets/23665302/24585873/6e661488-179d-11e7-8e81-ba27535715f4.png)

why players have ONLY ONE subject insted of 10 from config?

**Comment by BabelSolea** [comment]
upd my full config - what wrong with subjects?

```
timer: 300
votetimer: 15
waittimer: 60
wintimer: 15
loading:
  load-after-plugins: false
allow-fly-out-bounds: false
enable-subject-voting: true
restore-plots: true
scoreboard-update-delay: 20
max-vote-change: 3
max-particles: -1
names-after-voting: false
enable-item-drop: false
stats:
  enable: true
  save-delay: 400
  database:
    enable: true
    address: jdbc:mysql://localhost:3306/buildbattle?autoReconnect=true&useSSL=false
    user: root
    password: Hj7d0GjewPdM
    min-connections: 3
    max-connections: 16
particles:
  amount: 30
  offset:
    x: 0.5
    y: 0.5
    z: 0.5
subjects:
- 'Супергерои!'
- 'Домик'
- 'Фрукты'
- 'Крепость'
- 'Монеты'
- 'Котятки'
- 'Вкусняшки'
- 'Мобы'
- 'Цветы'
- 'Статуи'
scoreboards:
  main:
    enable: false
    worlds:
      enable:
      - world
  lobby:
    enable: true
  build:
    enable: true
  vote:
    enable: false
    text: false
  win:
    enable: true
blocked-entities:
- ender_crystal
- ender_dragon
- wither
blocks:
  blocked:
  - command
  - command_minecart
bossbar:
  color: green
  style: solid
mobs:
  enable-noai: true
  allow: true
chat:
  adjust: true
title:
  fade_in: 0
  stay: 60
  fade_out: 20
  syncronize: false
tab-list:
  adjust: true
voting:
  default-vote-points: 3
  second-slot:
    id: stained_clay:14
    points: 1
  third-slot:
    id: stained_clay:6
    points: 2
  fourth-slot:
    id: stained_clay:0
    points: 3
  fifth-slot:
    id: stained_clay:5
    points: 4
  sixth-slot:
    id: stained_clay:3
    points: 5
  seventh-slot:
    id: stained_clay:10
    points: 6
  eighth-slot:
    id: stained_clay:1
    points: 7
command-whitelist:
- give
- gamemode
timings:
  lobby-timer:
    at:
      '10':
      - tellraw @a ["",{"text":"Приготовьтесь!, ","color":"aqua"},{"text":", Игра скоро начнется!","color":"aqua"}]
  build-timer: {}
  vote-timer: {}
  win-timer: {}
join:
  time-change:
    change: false
    time: 6000
win-commands:
- null
hotbar:
  default:
    slot-1: stained_clay:0
    slot-2: stained_clay:14
    slot-3: stained_clay:1
    slot-4: stained_clay:4
    slot-5: stained_clay:5
    slot-6: stained_clay:3
    slot-7: stained_clay:11
    slot-8: stained_clay:10
    slot-9: air
money:
  first: 20
  second: 10
  third: 5
  others: 0
commands:
  first:
  - null
  second:
  - null
  third:
  - null
  others:
  - null
leave-item:
  slot: 0
  id: watch
subject-gui:
  item:
    id: paper
  subject-amount: 1
  slot: 8
bungeecord:
  enable: true
team-selection:
  show-names-as-lore: false
  item:
    id: paper
  team:
    '1':
      id: paper
    '2':
      id: paper
    '3':
      id: paper
    '4':
      id: paper
    '5':
      id: paper
    '6':
      id: paper
    '7':
      id: paper
    '8':
      id: paper
    '9':
      id: paper
    '10':
      id: paper
    '11':
      id: paper
    '12':
      id: paper
    '13':
      id: paper
    '14':
      id: paper
    '15':
      id: paper
    '16':
      id: paper
gui:
  slot: 8
  particles:
    id: red_rose
    enabled: true
  floor:
    id: hard_clay
    enabled: true
    excluded-blocks:
    - red_rose
  time:
    id: watch
    enabled: true
  rain:
    id: water_bucket
    enabled: true
  fly-speed:
    id: feather
    enabled: true
  heads:
    id: skull_item:3
    enabled: true
debug: false
clean-files: false

```

**Comment by BabelSolea** [comment]
that happens today when i add to all players permissiong bg.subjectmenu
they cuttently have to vote
but they have only 1 subject insted of 10
and game launch every match only that one subject!!!
"superheroes!" in english

that + hard lags make game boring and terrible for players =((((

**Comment by BabelSolea** [comment]
i fixed most errors from plugin showed today but i still have error with subjects!!!

[12:34:28 ERROR]: Could not pass event InventoryClickEvent to BuildingGame v4.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.Gui.update(Gui.java:167) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.SubjectMenu$1.actionPerformed(SubjectMenu.java:89) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.Gui.onInventoryClick(Gui.java:196) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	... 15 more

can ure help me??

**Comment by BabelSolea** [comment]
13:30:29 WARN]: [BuildingGame] Plugin BuildingGame v4.0.5 generated an exception while executing task 5196
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_121]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_121]
	at com.gmail.stefvanschiedev.buildinggame.managers.stats.StatManager.containsUUID(StatManager.java:74) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.events.stats.database.JoinPlayerStats$1.run(JoinPlayerStats.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by BabelSolea** [comment]
```
[13:30:42 WARN]: [BuildingGame] Plugin BuildingGame v4.0.5 generated an exception while executing task 5211
java.lang.NullPointerException
	at com.gmail.stefvanschiedev.buildinggame.events.stats.database.QuitPlayerStats$1.run(QuitPlayerStats.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by BabelSolea** [comment]
what do string

  subject-amount: -1

??

**Comment by BabelSolea** [comment]
oh really.

```
subject-gui:
  item:
    id: paper
  subject-amount: -1
  slot: 8
```

  subject-amount: -1
mean nubmer of defined subjects but not about item-stack in hotbar omg.

fixed i think....
