### ISSUE TITLE
log error spam pls fix and do next update FASTER

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#57]
```
[08:53:32 ERROR]: Could not pass event InventoryClickEvent to BuildingGame v4.0.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.Gui.update(Gui.java:167) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.SubjectMenu$1.actionPerformed(SubjectMenu.java:89) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.utils.guis.Gui.onInventoryClick(Gui.java:196) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BuildBattle01spigot.jar:git-Spigot-283de8b-aa522c9]
	... 15 more
```

**Comment by BabelSolea** [comment]
ure can update plugin EVERY day when ure something fix or add

pls do not collecting fixes and features!

release it that fast how ure add or change something!

**Comment by stefvanschie** [comment]
Marked the error as a bug.

I don't release updates whenever I change something, because a) I'm limited to max. two updates a day; b) more people will use outdated versions; c) people will report the same bugs/request the same features I've already noted; d) the plugin will be less stable; e) it takes more time than fixing multiple things before I release an update.
