### ISSUE TITLE
NullPointerException at QuitPlayerStats

### ISSUE THREAD

**Issue by cwkfr** [stefvanschie/buildinggame#58]
```
[10:02:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin BuildingGame v4.0.5 generated an
 exception while executing task 607832
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.gmail.stefvanschiedev.buildinggame.events.stats.database.QuitPlayerStats$1.run(QuitPl
ayerStats.java:24)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

Harmless. No problem with the game though.
I'm using MySQL

**Comment by cwkfr** [comment]
I don't know if this related but

```
[14:02:29 INFO]: [BuildingGame] Loading files
[14:02:29 INFO]: [BuildingGame] Loading arenas
[14:02:29 INFO]: [BuildingGame] Loading plots
[14:02:30 INFO]: [BuildingGame] Loading main spawn
[14:02:30 INFO]: [BuildingGame] Loading soft dependencies
[14:02:30 INFO]: [BuildingGame] Loading commands
[14:02:30 INFO]: [BuildingGame] Loading stats
[14:02:30 INFO]: [BuildingGame] Configuring connection pool...
[14:02:30 INFO]: [BuildingGame] Creating BoneCP Configuration...
[14:02:30 INFO]: [BuildingGame] Setting up MySQL Connection pool...
[14:02:30 INFO]: [BuildingGame] Connection pool successfully configured.
[14:02:30 INFO]: [BuildingGame] Total connections ==> 10
[14:02:30 WARN]: **[BuildingGame] Error while retrieving data from database**
[14:02:30 INFO]: [BuildingGame] Loading listeners
[14:02:30 INFO]: [BuildingGame] Loading signs
[14:02:30 INFO]: [BuildingGame] Loading timer
[14:02:30 INFO]: [BuildingGame] BuildingGame has been enabled in 527 milliseconds!
```

**Comment by stefvanschie** [comment]
Please check if all the setting in the config regarding the database are correct.
