### ISSUE TITLE
Spam + Vote issue

### ISSUE THREAD

**Issue by cwkfr** [stefvanschie/buildinggame#59]
I'm running spigot 1.10 and using MySQL.

Player spam vote too much when voting other's plot, is there any option to make it one-time vote or at least a delay to change your vote?

And for some reason, this error just pops up and players are able to place the voting block to the plot.

```
[Server thread/WARN]: [BuildingGame] Task #336084 for BuildingGame v4.0.5 generated an exception
java.lang.NullPointerException
	at com.gmail.stefvanschiedev.buildinggame.utils.plot.Plot.addVote(Plot.java:168) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.timers.VoteTimer.run(VoteTimer.java:295) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-570526c-c1b529e]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-570526c-c1b529e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by stefvanschie** [comment]
Set the max-vote-change to 1 to limit the amount of votes.
