### ISSUE TITLE
java.lang.NoClassDefFoundError: fr/rhaz/socket4mc/Socket4MC

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#62]
Building Game version: 4.0.6. Running Paper 1.11.2

This is the error seen on console:

```
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading files
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading arenas
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading plots
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading main spawn
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading soft dependencies
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading commands
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading stats
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading listeners
[21:46:44] [Server thread/INFO]: [BuildingGame] Loading signs
[21:46:44] [Server thread/WARN]: [BuildingGame] Task #5 for BuildingGame v4.0.6 generated an exception
java.lang.NoClassDefFoundError: fr/rhaz/socket4mc/Socket4MC
        at com.gmail.stefvanschiedev.buildinggame.utils.bungeecord.BungeeCordHandler.send(BungeeCordHandler.java:39) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.bungeecord.BungeeCordHandler.sign(BungeeCordHandler.java:56) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateJoinSigns(SignManager.java:134) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateJoinSigns(SignManager.java:100) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateSigns(SignManager.java:95) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.setup(SignManager.java:86) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.Main.loadPlugin(Main.java:221) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.ja
r:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1081]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: fr.rhaz.socket4mc.Socket4MC
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1081]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
        ... 15 more
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading files
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading arenas
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading plots
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading main spawn
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading soft dependencies
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading commands
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading stats
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading listeners
[21:46:45] [Server thread/INFO]: [BuildingGame] Loading signs
[21:46:45] [Server thread/WARN]: [BuildingGame] Task #5 for BuildingGame v4.0.6 generated an exception
java.lang.NoClassDefFoundError: fr/rhaz/socket4mc/Socket4MC
        at com.gmail.stefvanschiedev.buildinggame.utils.bungeecord.BungeeCordHandler.send(BungeeCordHandler.java:39) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.utils.bungeecord.BungeeCordHandler.sign(BungeeCordHandler.java:56) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateJoinSigns(SignManager.java:134) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateJoinSigns(SignManager.java:100) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.updateSigns(SignManager.java:95) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.managers.arenas.SignManager.setup(SignManager.java:86) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.Main.loadPlugin(Main.java:221) ~[?:?]
        at com.gmail.stefvanschiedev.buildinggame.timers.LoadCooldown.run(LoadCooldown.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1081]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.ja
r:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1081]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1081]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

This repeats endlessly.

**Comment by stefvanschie** [comment]
I think in your config.yml bungeecord is enabled, but you don't have Socket4MC. Try disabling bungeecord and see if it helps.

**Comment by zedwick** [comment]
Thanks that did resolve it for me.
