### ISSUE TITLE
issue with voting and exception executing task n° xx

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#66]
ath the end of the game the voting system doesn't work. If i vote the other players, the vote is assigned to me also.

At regular interval there are exception errors like this:
[18:14:37 WARN]: [BuildingGame] Plugin BuildingGame v4.0.6 generated an exception while executing task 70
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_121]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_121]
	at com.gmail.stefvanschiedev.buildinggame.managers.stats.StatManager.saveToFile(StatManager.java:123) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.timers.StatSaveTimer.run(StatSaveTimer.java:12) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[build-1.11.2.jar:git-Spigot-38ddb34-c19c293]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [build-1.11.2.jar:git-Spigot-38ddb34-c19c293]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

My used plugin is:
AsyncWorldEditInjector, WorldEdit, EmptyWorldGenerator, SimpleBroadcast, Essentials, NametagEdit, WorldGuard, Multiverse-Core, SimpleBackup, AsyncWorldEdit, EssentialsChat, EssentialsGeoIP, PermissionsEx, hub, CustomJoinItems, SuperVanish, Vault, IPUserAccess, EssentialsSpawn, WorldEditSelectionVisualizer, TitleManager, BuildingGame, HolographicDisplays, Citizens, ChestCommands, CompatNoCheatPlus, NoCheatPlus, EditableSign

**Comment by stefvanschie** [comment]
The voting issue will hopefully be resolved in the next version. I thought I fixed the second issue already, but apparently not, so I will fix that one now.

**Comment by afronights** [comment]
thank u !!!!

**Comment by stefvanschie** [comment]
Fixed in version 4.0.7
