### ISSUE TITLE
exception error while execution task xxx and problem with voting

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#68]
Again exception error:
[BuildingGame] Plugin BuildingGame v4.0.7 generated an exception while executing task 988
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_121]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_121]
	at com.gmail.stefvanschiedev.buildinggame.managers.stats.StatManager.saveToFile(StatManager.java:116) ~[?:?]
	at com.gmail.stefvanschiedev.buildinggame.timers.StatSaveTimer.run(StatSaveTimer.java:12) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[build-1.11.2.jar:git-Spigot-38ddb34-c19c293]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [build-1.11.2.jar:git-Spigot-38ddb34-c19c293]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

and problem with voting ...

**Comment by stefvanschie** [comment]
Verified and fixed in the next version

**Comment by stefvanschie** [comment]
Fixed in version 5.0.0.
